---
title: "An Analysis of the Racial Wage Gap"
author:
- name: Zachary Bisson
  email: zachary.bisson@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
- name: Anna Elfstrum
  email: anna.elfstrum@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
- name: Shawn Graven
  email: shawn.graven@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
- name: Jack Kuivanen
  email: jack.kuivanen@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
- name: Caleb Olson
  email: caleb.olson@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
- name: Kate Soukkala
  email: katelyn.soukkala@my.uwrf.edu
  affiliation: University of Wisconsin-River Falls
  footnote: 2
date: "`r Sys.Date()`"
output:
  pdf_document: rticles::elsevier_article
  html_document: default
footnote:
- code: 2
  text: Equal contribution, author order is alphabetical
abstract: |
  “More than half of whites — 55 percent — surveyed say that, generally speaking, they believe there is discrimination against white people in America today” [@gonyea2017majority].  What is true and what is real are becoming harder and harder to decern.  When it comes to the claims (or negations) of a wage gap existing between dominant and non-dominant races it is no different.  Here, using statistical analysis tools on data from the Economic Policy Institute, we have found that a statistically significant gap does exist.  
  
  In the following sections you will find a basic [introduction](#introduction), [literature review](#literature-review), [theoretical analysis](#theoretical-analysis), [empirical analysis](#empirical-analysis), [conclusion](#conclusion), and finally a list of [references](#references) cited within this work.  The [literature review](#literature-review) contains a broad overview of what we found in our initial research and our [theoretical analysis](#theoretical-analysis) sets up the questions and hypothesis tests that we perform in the empirical analysis.  Lastly, we have our [conclusion](#conclusion) which sums up our findings clearly and concisely.  
journal: Econometrics (ECON 426)
address:
- code: University of Wisconsin-River Falls
  address: University of Wisconsin-River Falls, 410 South Third Street, River Falls,
    WI, 54022
bibliography: citations.bib
numbersections: yes
csl: core/elsevier-harvard.csl
preamble: |
  \usepackage{natbib}
editor_options:
  markdown:
    wrap: 100
---

```{r, eval=FALSE, echo=FALSE, include=FALSE}
file.edit("markdown/_head.Rmd")
file.edit("markdown/Export.Rmd")
file.edit("markdown/importAndClean.Rmd")
```


```{r, child="markdown/_head.Rmd"}
```



# Introduction
```{r, child="markdown/Introduction.Rmd"}
```


# Literature Review

```{r, child="markdown/LitReview.Rmd"}

```

# Theoretical Analysis

```{r, child="markdown/TheoreticalAnalysis.Rmd"}
```

# Empirical Analysis

## Data
```{r, child='markdown/importAndClean.Rmd'}
```

```{r, child='markdown/Export.Rmd'}
```

## Methodology

```{r, child="markdown/Methodology.Rmd"}
```

## Results

```{r, child='markdown/Estimators.Rmd'}
```


# Conclusion
```{r, child='markdown/Conclusion.Rmd'}
```

# References
<!-- All of you references should be stored in BibTeX format in the file ../bib_file.bib -->
