### Using the Data

After acquiring all the data, the next step was cleaning all the data. Once the data is cleaned and reorganized the next was filtering it for all the different hypothesis. Once the data was separated into the different races and age groups the data is then represented in the form of graphs demonstrating the how the different races compare to each other on a median income basis. The graphs however do not demonstrate our hypothesis well enough.

Following the graphs is chow testing. After preforming the first chow test we can reject our null hypothesis that there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of white individuals who are 16 and older in the United States. This is due to the p-value being less than `.01`.

The second chow test also results in a rejection of our null hypothesis demonstrating there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of black individuals who are 16 and older in the United States. Since the p-value is less than 0.01, we can conclude that the median income of black individuals aged 16 and older in the United States is significantly lower than the median income of individuals aged 16 and older.

The final chow test results again in a rejection of the null hypothesis. This claims that there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of Hispanic individuals who are 16 and older in the United States. We can then conclude that the median income of Hispanic individuals aged 16 and older in the United States is significantly lower than the median income of individuals aged 16 and older. Following the chow testing concludes our hypothesis on the data that whites make more on a median income basis than average United States residents and that black people and Hispanics also make less median income than the average United States resident.

### Open Sorce
This document is created open source, meaning anyone can view the code, comment on it, and suggest modifications to the documents.  As such, the RMarkdown used to create these documents, both HTML and PDF are available at https://github.com/zekrom-vale/IncomeOnRace as well as all modifications in the repository.  Both versions are are created with the same multi-file RMarkdown using `knitr` to knit statically with PDF or interactively with HTML.  The most up to date version of the PDF and HTML versions will be available there.  The GitHub repository also archives the data we used after it was cleaned in csv format.

### HTML Version
An interactive HTML document / web site is available at https://zekrom-vale.github.io/IncomeOnRace/ and is recommended over the static PDF version.  The HTML version uses the package `plotly` that allows users to zoom, filter, play animations, and inspect data in graphs.  The static PDF version uses `ggplot2` that does not support interactivity.