## Hyppothesises
### White

$$H_0 : White Income \propto AllIncome$$

Our null hypothesis is that there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of white individuals who are 16 and older in the United States.  


$$H_A : White Income \not\propto AllIncome$$

### Black

Our alternate hypothesis is that the median income of white individuals aged 16 and older in the United States is significantly lower than the median income of individuals aged 16 and older. 


$$H_0 : Black Income \propto AllIncome$$

Our null hypothesis is that there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of black individuals who are 16 and older in the United States.  

$$H_A : Black Income \not\propto AllIncome$$

### Hispanic

Our alternate hypothesis is that the median income of hispanic individuals aged 16 and older in the United States is significantly lower than the median income of individuals aged 16 and older. 


$$H_0 : Hispanic Income \propto AllIncome$$

Our null hypothesis is that there is no significant difference between the median income of individuals aged 16 and older in the United States and the median income of hispanic individuals who are 16 and older in the United States.  


$$H_A : Hispanic Income \not\propto AllIncome$$

Our alternate hypothesis is that the median income of black individuals aged 16 and older in the United States is significantly lower than the median income of individuals aged 16 and older. 

## Models
Our model is simple, `mod1` predicting `Median` only depends on the `Date`.  `mod2` preforms the $\log(Median)$ as it makes the data more linear as monetary values tends to fit log regressions much better than linear ones.  These will represent $AllIncome$.  `modBlack` includes the `Black` factor and will represent the Black population and non-black's.  The same is done with `modWhite` and `modHispanic` with the white's and the hispanics respectively.

$$mod1 : Median=\beta_1Date+\beta_0+e$$
$$mod2 : \log(Median)=\beta_1Date+\beta_0+e$$
$$modWhite : \log(Median)=\beta_1Date*White+\beta_0+e$$
$$modBlack : \log(Median)=\beta_1Date*Black+\beta_0+e$$
$$modBlack : \log(Median)=\beta_1Date*Hispanic+\beta_0+e$$
